on: [push]
jobs:
  SonarBuildBreaker:
    runs-on: ubuntu-latest
    name: SonarBuildBreaker
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Sonar Build Breaker
        uses: ./ 
        id: buildbreaker
        with:
          sonar_url: 'https://sonarcloud.io'
          sonar_branch: 'main'
          sonar_token: ${{ secrets.SONAR_TOKEN }}
          project_key: 'sonar_test_github_project'
